name: CI

on: [push, pull_request]

jobs:
    unix-test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                emacs-version:
                    - 26.3
                    - 27.2
                    - 28.1
                    - snapshot

        steps:
            - uses: actions/checkout@v2

            - uses: jcs090218/setup-emacs@master
              with:
                  version: ${{ matrix.emacs-version }}

            - uses: actions/setup-node@v2
              with:
                node-version: '16'

            - uses: emacs-eask/setup-eask@master
              with:
                version: 'snapshot'

            - name: Install requirements
              if: matrix.os == 'ubuntu-latest'
              run: |
                  echo "$HOME/.cask/bin" >> $GITHUB_PATH
                  echo "$HOME/bin" >> $GITHUB_PATH

                  sudo apt update
                  sudo apt install -y gnutls-bin gnupg2 dirmngr
                  sudo apt install -y texinfo libgif-dev libxpm-dev

            - name: Install needed rust stuff
              if: matrix.os == 'ubuntu-latest'
              run: |
                  curl -sSf https://build.travis-ci.com/files/rustup-init.sh | sh -s -- --default-toolchain=stable -y
                  source $HOME/.cargo/env
                  rustup component add rustfmt-preview

            - name: rustic-doc prerequisites
              if: matrix.os == 'ubuntu-latest'
              run: |
                   wget https://github.com/jgm/pandoc/releases/download/2.17.0.1/pandoc-2.17.0.1-1-amd64.deb
                   sudo dpkg -i pandoc-2.17.0.1-1-amd64.deb
                   mkdir -p ~/.local/bin
                   mkdir -p ~/.local/share/emacs/rustic-doc/std/
                   curl -sL https://github.com/sharkdp/fd/releases/download/v8.3.2/fd-v8.3.2-x86_64-unknown-linux-musl.tar.gz | tar xz --wildcards --strip-components=1 -C /usr/local/bin '*/fd'
                   curl -sL https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz | tar xz --wildcards --strip-components=1 -C /usr/local/bin '*/rg'
                   rustup component add rust-docs

            - name: Run tests
              run: |
                make ci
